#!/usr/bin/env bash

# Get list of all processes and their details
process_list=$(ps -e -o pid,ppid,user,cmd --no-headers)

# Print the header
printf "%-8s %-8s %-10s %s\n" "PID" "PPID" "USER" "COMMAND"

# Loop through the list of processes and print details
while read -r line; do
  pid=$(echo "$line" | awk '{print $1}')
  ppid=$(echo "$line" | awk '{print $2}')
  user=$(echo "$line" | awk '{print $3}')
  cmd=$(echo "$line" | awk '{print $4}')
  printf "%-8s %-8s %-10s %s\n" "$pid" "$ppid" "$user" "$cmd"
done <<< "$process_list"
